version: "3.7"

services:
  graphic_generator:
    container_name: graphic_generator
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: "yarn start"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    networks:
      - graphic_generator_network

networks:
  graphic_generator_network:
